#!/bin/bash
# scripts/lib/pr-comment-formatter.sh
# Transform parsed TOME findings (JSON) into GitHub-compatible markdown.
#
# USAGE:
#   tome-parser.sh <tome_path> | pr-comment-formatter.sh [config_json]
#
# INPUT: JSON array of findings from stdin (piped from tome-parser.sh)
# ARGS:  $1 = optional config JSON string with:
#          severity_filter:      array of severities to include (default: ["P1","P2","P3"])
#          confidence_threshold: minimum confidence_score (default: 0)
#          max_findings:         cap on findings per comment (default: 30)
#          include_traces:       include code traces (default: true)
#          include_fix_suggestions: include fix text (default: true)
#          collapse_threshold:   collapse section if > N findings (default: 5)
#          footer:               include Rune footer (default: true)
# OUTPUT: GitHub-compatible markdown to stdout
#
# FEATURES:
#   - Collapsible <details> sections for P1/P2, table for P3
#   - Severity badges (red circle P1, yellow circle P2, chart P3)
#   - <!-- rune-review-findings --> marker for idempotency
#   - GitHub 65,000 char limit handling with truncation
#   - Rune footer with version and timestamp
#
# COMPAT: Uses grep -E (not grep -P) and sed -E (not sed -r) for macOS.
# REQUIRES: jq (guarded)

set -euo pipefail

# Guard jq availability
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required but not found. Install via: brew install jq" >&2
  exit 1
fi

# --- Read Input ---

findings_json=$(cat)

# Validate input is a JSON array
if ! printf '%s' "$findings_json" | jq -e 'type == "array"' &>/dev/null; then
  echo "ERROR: Input must be a JSON array of findings" >&2
  exit 1
fi

# --- Parse Config ---

config_json="${1:-{}}"
# Validate config is valid JSON
if ! printf '%s' "$config_json" | jq -e '.' &>/dev/null; then
  config_json='{}'
fi

severity_filter=$(printf '%s' "$config_json" | jq -r '.severity_filter // ["P1","P2","P3"] | @json')
confidence_threshold=$(printf '%s' "$config_json" | jq -r '.confidence_threshold // 0')
max_findings=$(printf '%s' "$config_json" | jq -r '.max_findings // 30')
include_traces=$(printf '%s' "$config_json" | jq -r '.include_traces // true')
include_fix=$(printf '%s' "$config_json" | jq -r '.include_fix_suggestions // true')
collapse_threshold=$(printf '%s' "$config_json" | jq -r '.collapse_threshold // 5')
show_footer=$(printf '%s' "$config_json" | jq -r '.footer // true')

# --- Filter Findings ---

filtered=$(printf '%s' "$findings_json" | jq \
  --argjson sev "$severity_filter" \
  --argjson conf_thresh "$confidence_threshold" \
  --argjson max_count "$max_findings" \
  '[.[] | select(
    (.severity as $s | $sev | index($s) != null) and
    ((.confidence_score // 0) >= $conf_thresh)
  )] | .[:$max_count]')

total_filtered=$(printf '%s' "$filtered" | jq 'length')
total_original=$(printf '%s' "$findings_json" | jq 'length')

if [[ "$total_filtered" -eq 0 ]]; then
  # No findings after filtering — output minimal comment
  cat <<'EMPTY_EOF'
<!-- rune-review-findings -->
## Rune Review Summary

No findings to report after applying filters.

---

EMPTY_EOF
  if [[ "$show_footer" == "true" ]]; then
    printf '*Generated by Rune · %s*\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  fi
  exit 0
fi

# --- Count by Severity ---

p1_count=$(printf '%s' "$filtered" | jq '[.[] | select(.severity == "P1")] | length')
p2_count=$(printf '%s' "$filtered" | jq '[.[] | select(.severity == "P2")] | length')
p3_count=$(printf '%s' "$filtered" | jq '[.[] | select(.severity == "P3")] | length')

# Collect unique ash names
ash_names=$(printf '%s' "$filtered" | jq -r '[.[] | .ash | select(. != null and . != "")] | unique | join(", ")')

# --- Build Output ---

output=""

_append() {
  output="${output}${1}
"
}

# Idempotency marker
_append "<!-- rune-review-findings -->"
_append ""
_append "## Rune Review Summary"
_append ""

# Ash names line
if [[ -n "$ash_names" ]]; then
  _append "**Reviewed by**: ${ash_names}"
fi

# Finding counts
counts=""
if [[ "$p1_count" -gt 0 ]]; then counts="${counts}${p1_count} P1 (Critical)"; fi
if [[ "$p2_count" -gt 0 ]]; then
  if [[ -n "$counts" ]]; then counts="${counts} · "; fi
  counts="${counts}${p2_count} P2 (High)"
fi
if [[ "$p3_count" -gt 0 ]]; then
  if [[ -n "$counts" ]]; then counts="${counts} · "; fi
  counts="${counts}${p3_count} P3 (Info)"
fi
_append "**Findings**: ${counts}"

if [[ "$total_filtered" -lt "$total_original" ]]; then
  _append "**Filtered**: Showing ${total_filtered} of ${total_original} total findings"
fi

_append ""
_append "---"
_append ""

# --- Render P1 Findings ---

_render_finding_detail() {
  local finding="$1"
  local fid ffile fline fsev fconf fconf_score ftitle fbody fash

  fid=$(printf '%s' "$finding" | jq -r '.id')
  ffile=$(printf '%s' "$finding" | jq -r '.file // ""')
  fline=$(printf '%s' "$finding" | jq -r '.line // ""')
  fsev=$(printf '%s' "$finding" | jq -r '.severity')
  fconf=$(printf '%s' "$finding" | jq -r '.confidence // ""')
  fconf_score=$(printf '%s' "$finding" | jq -r '.confidence_score // ""')
  ftitle=$(printf '%s' "$finding" | jq -r '.title // ""')
  fbody=$(printf '%s' "$finding" | jq -r '.body // ""')
  fash=$(printf '%s' "$finding" | jq -r '.ash // ""')

  # Build location string
  local location=""
  if [[ -n "$ffile" ]]; then
    location="$ffile"
    if [[ -n "$fline" && "$fline" != "null" ]]; then
      location="${location}:${fline}"
    fi
  fi

  # Summary line
  local summary="**[${fid}] ${ftitle}**"
  if [[ -n "$location" ]]; then
    summary="${summary} — \`${location}\`"
  fi

  _append "<details>"
  _append "<summary>${summary}</summary>"
  _append ""

  # Metadata line
  local meta=""
  if [[ -n "$fash" ]]; then meta="**Ash**: ${fash}"; fi
  if [[ -n "$fconf" ]]; then
    if [[ -n "$meta" ]]; then meta="${meta} · "; fi
    meta="${meta}**Confidence**: ${fconf}"
    if [[ -n "$fconf_score" && "$fconf_score" != "null" ]]; then
      meta="${meta} (${fconf_score})"
    fi
  fi
  if [[ -n "$meta" ]]; then
    _append "$meta"
    _append ""
  fi

  # Body (issue/fix/traces)
  if [[ -n "$fbody" && "$include_traces" == "true" ]]; then
    _append "$fbody"
    _append ""
  fi

  _append "</details>"
  _append ""
}

# --- P1 Section ---

if [[ "$p1_count" -gt 0 ]]; then
  _append "### P1 — Critical (${p1_count})"
  _append ""

  p1_findings=$(printf '%s' "$filtered" | jq -c '[.[] | select(.severity == "P1")]')
  p1_len=$(printf '%s' "$p1_findings" | jq 'length')

  for i in $(seq 0 $(( p1_len - 1 ))); do
    finding=$(printf '%s' "$p1_findings" | jq -c ".[$i]")
    _render_finding_detail "$finding"
  done
fi

# --- P2 Section ---

if [[ "$p2_count" -gt 0 ]]; then
  _append "### P2 — High (${p2_count})"
  _append ""

  p2_findings=$(printf '%s' "$filtered" | jq -c '[.[] | select(.severity == "P2")]')
  p2_len=$(printf '%s' "$p2_findings" | jq 'length')

  if [[ "$p2_len" -gt "$collapse_threshold" ]]; then
    # Collapse if over threshold
    _append "<details>"
    _append "<summary>Show ${p2_len} P2 findings</summary>"
    _append ""
  fi

  for i in $(seq 0 $(( p2_len - 1 ))); do
    finding=$(printf '%s' "$p2_findings" | jq -c ".[$i]")
    _render_finding_detail "$finding"
  done

  if [[ "$p2_len" -gt "$collapse_threshold" ]]; then
    _append "</details>"
    _append ""
  fi
fi

# --- P3 Section (Collapsed Table) ---

if [[ "$p3_count" -gt 0 ]]; then
  _append "---"
  _append ""
  _append "<details>"
  _append "<summary>P3 — Info (${p3_count} findings, collapsed)</summary>"
  _append ""
  _append "| ID | Title | File | Confidence |"
  _append "|----|-------|------|------------|"

  p3_findings=$(printf '%s' "$filtered" | jq -c '[.[] | select(.severity == "P3")]')
  p3_len=$(printf '%s' "$p3_findings" | jq 'length')

  for i in $(seq 0 $(( p3_len - 1 ))); do
    local_fid=$(printf '%s' "$p3_findings" | jq -r ".[$i].id")
    local_ftitle=$(printf '%s' "$p3_findings" | jq -r ".[$i].title // \"\"" | head -c 80)
    local_ffile=$(printf '%s' "$p3_findings" | jq -r ".[$i].file // \"\"")
    local_fline=$(printf '%s' "$p3_findings" | jq -r ".[$i].line // \"\"")
    local_fconf=$(printf '%s' "$p3_findings" | jq -r ".[$i].confidence // \"\"")

    local_loc="$local_ffile"
    if [[ -n "$local_fline" && "$local_fline" != "null" ]]; then
      local_loc="${local_loc}:${local_fline}"
    fi

    _append "| ${local_fid} | ${local_ftitle} | ${local_loc} | ${local_fconf} |"
  done

  _append ""
  _append "</details>"
  _append ""
fi

# --- Footer ---

_append "---"
_append ""
if [[ "$show_footer" == "true" ]]; then
  timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  _append "*Generated by Rune · ${timestamp}*"
  _append "*Run \`/rune:mend\` to auto-fix these findings*"
fi

# --- GitHub Character Limit Handling ---

GITHUB_COMMENT_LIMIT=65000

output_len=${#output}

if [[ "$output_len" -gt "$GITHUB_COMMENT_LIMIT" ]]; then
  # Strategy 1: Truncate P3 table to first 10 entries
  # (Rebuild is complex; instead, hard-truncate with notice)
  truncated="${output:0:$GITHUB_COMMENT_LIMIT}"

  # Find last complete line
  truncated=$(printf '%s' "$truncated" | head -c "$GITHUB_COMMENT_LIMIT")

  # Append truncation notice
  output="${truncated}

---

> **Note**: Comment truncated due to GitHub's 65,000 character limit. Full findings available in TOME file.

*Generated by Rune · $(date -u +%Y-%m-%dT%H:%M:%SZ)*"
fi

# Output final markdown
printf '%s' "$output"
