#!/usr/bin/env bash
# test-arc-hierarchy-stop-hook.sh — Tests for arc-hierarchy-stop-hook.sh jq queries
#
# Validates the fix for the .plan/.depends_on field name mismatch bug:
#   - JSON exec table uses .path and .requires
#   - Stop hook jq queries previously used .plan and .depends_on (silent failures)
#   - Fix: queries now use .path, .requires, and endswith() matching for CURRENT_CHILD
#
# Usage: bash plugins/rune/scripts/tests/test-arc-hierarchy-stop-hook.sh
# Exit: 0 on all pass, 1 on any failure.

set -euo pipefail

# ── Resolve paths ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_SCRIPT="$(cd "$SCRIPT_DIR/.." && pwd)/arc-hierarchy-stop-hook.sh"
LIB_DIR="$(cd "$SCRIPT_DIR/../lib" && pwd)"

# ── Temp directory for isolation ──
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# ── Test framework ──
PASS_COUNT=0
FAIL_COUNT=0
TOTAL_COUNT=0

assert_eq() {
  local test_name="$1"
  local expected="$2"
  local actual="$3"
  TOTAL_COUNT=$(( TOTAL_COUNT + 1 ))
  if [[ "$expected" = "$actual" ]]; then
    PASS_COUNT=$(( PASS_COUNT + 1 ))
    printf "  PASS: %s\n" "$test_name"
  else
    FAIL_COUNT=$(( FAIL_COUNT + 1 ))
    printf "  FAIL: %s\n" "$test_name"
    printf "    expected: %q\n" "$expected"
    printf "    actual:   %q\n" "$actual"
  fi
}

assert_contains() {
  local test_name="$1"
  local needle="$2"
  local haystack="$3"
  TOTAL_COUNT=$(( TOTAL_COUNT + 1 ))
  if [[ "$haystack" == *"$needle"* ]]; then
    PASS_COUNT=$(( PASS_COUNT + 1 ))
    printf "  PASS: %s\n" "$test_name"
  else
    FAIL_COUNT=$(( FAIL_COUNT + 1 ))
    printf "  FAIL: %s (needle not found)\n" "$test_name"
    printf "    needle:   %q\n" "$needle"
    printf "    haystack: %q\n" "$haystack"
  fi
}

assert_not_contains() {
  local test_name="$1"
  local needle="$2"
  local haystack="$3"
  TOTAL_COUNT=$(( TOTAL_COUNT + 1 ))
  if [[ "$haystack" != *"$needle"* ]]; then
    PASS_COUNT=$(( PASS_COUNT + 1 ))
    printf "  PASS: %s\n" "$test_name"
  else
    FAIL_COUNT=$(( FAIL_COUNT + 1 ))
    printf "  FAIL: %s (needle was found but should not be)\n" "$test_name"
    printf "    needle:   %q\n" "$needle"
    printf "    haystack: %q\n" "$haystack"
  fi
}

# ── Guard: jq required ──
if ! command -v jq &>/dev/null; then
  printf "SKIP: jq not available\n"
  exit 0
fi

# ═══════════════════════════════════════════════════════════════
# Test fixtures — exec table JSON schemas
# ═══════════════════════════════════════════════════════════════

# Canonical schema (.path, .requires, .provides) — as generated by LLM
EXEC_TABLE_CANONICAL='{
  "children": [
    {
      "seq": 1,
      "path": "plans/children/01-fix-bugs-plan.md",
      "status": "completed",
      "requires": [],
      "provides": ["bug-fixed", "tests-passing"]
    },
    {
      "seq": 2,
      "path": "plans/children/02-core-feature-plan.md",
      "status": "pending",
      "requires": ["bug-fixed", "tests-passing"],
      "provides": ["core-feature", "api-ready"]
    },
    {
      "seq": 3,
      "path": "plans/children/03-integration-plan.md",
      "status": "pending",
      "requires": ["core-feature", "api-ready"],
      "provides": ["integration-done"]
    },
    {
      "seq": 4,
      "path": "plans/children/04-independent-plan.md",
      "status": "pending",
      "requires": [],
      "provides": ["docs-updated"]
    }
  ],
  "completed_provides": ["bug-fixed", "tests-passing"],
  "updated_at": "2026-03-15T10:00:00Z"
}'

# Legacy schema (.plan, .depends_on) — as originally specified in pseudocode
EXEC_TABLE_LEGACY='{
  "children": [
    {
      "seq": 1,
      "plan": "01-fix-bugs-plan.md",
      "status": "completed",
      "depends_on": [],
      "provides": ["bug-fixed", "tests-passing"]
    },
    {
      "seq": 2,
      "plan": "02-core-feature-plan.md",
      "status": "pending",
      "depends_on": ["01-fix-bugs-plan.md"],
      "provides": ["core-feature", "api-ready"]
    },
    {
      "seq": 3,
      "plan": "03-integration-plan.md",
      "status": "pending",
      "depends_on": ["02-core-feature-plan.md"],
      "provides": ["integration-done"]
    }
  ],
  "completed_provides": ["bug-fixed", "tests-passing"],
  "updated_at": "2026-03-15T10:00:00Z"
}'

# ═══════════════════════════════════════════════════════════════
# 1. Topological sort — next executable child (.path + .requires)
# ═══════════════════════════════════════════════════════════════
printf "\n=== Topological sort: next executable child ===\n"

# The jq query extracted from the stop hook (lines 451-462):
TOPO_SORT_QUERY='
  [.children[] | select(.status == "completed") | (.provides // [])[]] as $provided |
  [
    .children[] |
    select(.status == "pending") |
    select(
      (.requires // []) | all(. as $req | $provided | any(. == $req))
    )
  ] | first | .path // empty
'

# 1a. Canonical schema: child 02 should be next (requires satisfied by child 01)
result=$(echo "$EXEC_TABLE_CANONICAL" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Canonical: child 02 is next (requires satisfied)" \
  "plans/children/02-core-feature-plan.md" "$result"

# 1b. Canonical schema: child 04 also executable (no requires)
# But child 02 comes first in array order
result=$(echo "$EXEC_TABLE_CANONICAL" | jq -r '
  [.children[] | select(.status == "completed") | (.provides // [])[]] as $provided |
  [
    .children[] |
    select(.status == "pending") |
    select(
      (.requires // []) | all(. as $req | $provided | any(. == $req))
    )
  ] | length
' 2>/dev/null || echo "0")
assert_eq "Canonical: 2 children executable (02 and 04)" "2" "$result"

# 1c. When no children completed, only no-requires children are executable
ALL_PENDING='{
  "children": [
    {"seq": 1, "path": "plans/children/01-a.md", "status": "pending", "requires": ["x"], "provides": ["a"]},
    {"seq": 2, "path": "plans/children/02-b.md", "status": "pending", "requires": [], "provides": ["b"]}
  ]
}'
result=$(echo "$ALL_PENDING" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "No completed: only no-requires child is executable" \
  "plans/children/02-b.md" "$result"

# 1d. All children completed — no next child
ALL_DONE='{
  "children": [
    {"seq": 1, "path": "plans/children/01-a.md", "status": "completed", "requires": [], "provides": ["a"]}
  ]
}'
result=$(echo "$ALL_DONE" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "All completed: no next child (empty)" "" "$result"

# 1e. Partial requires satisfied — not executable
PARTIAL_DEPS='{
  "children": [
    {"seq": 1, "path": "plans/children/01-a.md", "status": "completed", "requires": [], "provides": ["a"]},
    {"seq": 2, "path": "plans/children/02-b.md", "status": "pending", "requires": ["a", "missing-dep"], "provides": ["b"]}
  ]
}'
result=$(echo "$PARTIAL_DEPS" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Partial requires: child NOT executable" "" "$result"

# 1f. Missing .requires field defaults to empty (no deps = always executable)
NO_REQUIRES_FIELD='{
  "children": [
    {"seq": 1, "path": "plans/children/01-a.md", "status": "pending", "provides": ["a"]}
  ]
}'
result=$(echo "$NO_REQUIRES_FIELD" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Missing .requires field: defaults to executable" \
  "plans/children/01-a.md" "$result"

# ═══════════════════════════════════════════════════════════════
# 2. Deadlock detection (.path + .requires)
# ═══════════════════════════════════════════════════════════════
printf "\n=== Deadlock detection ===\n"

# The jq query extracted from the stop hook (lines 476-486):
DEADLOCK_QUERY='
  [.children[] | select(.status == "completed") | (.provides // [])[]] as $provided |
  [
    .children[] |
    select(.status == "pending") |
    select(
      (.requires // []) | any(. as $req | $provided | any(. == $req) | not)
    ) |
    .path
  ] | join(", ")
'

# 2a. Child 03 blocked (needs core-feature from child 02 which is pending)
result=$(echo "$EXEC_TABLE_CANONICAL" | jq -r "$DEADLOCK_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Deadlock query: child 03 is blocked" \
  "plans/children/03-integration-plan.md" "$result"

# 2b. No deadlock when all deps satisfied
ALL_SATISFIED='{
  "children": [
    {"seq": 1, "path": "a.md", "status": "completed", "requires": [], "provides": ["x", "y"]},
    {"seq": 2, "path": "b.md", "status": "pending", "requires": ["x"], "provides": []}
  ]
}'
result=$(echo "$ALL_SATISFIED" | jq -r "$DEADLOCK_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "No deadlock: blocked list is empty" "" "$result"

# 2c. True deadlock: circular dependency (A needs B, B needs A)
CIRCULAR='{
  "children": [
    {"seq": 1, "path": "a.md", "status": "pending", "requires": ["from-b"], "provides": ["from-a"]},
    {"seq": 2, "path": "b.md", "status": "pending", "requires": ["from-a"], "provides": ["from-b"]}
  ]
}'
result=$(echo "$CIRCULAR" | jq -r "$DEADLOCK_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Circular deadlock: both children blocked" "a.md, b.md" "$result"

# 2d. Deadlock with missing provides (completed child didn't provide what's needed)
MISSING_PROVIDES='{
  "children": [
    {"seq": 1, "path": "a.md", "status": "completed", "requires": [], "provides": ["x"]},
    {"seq": 2, "path": "b.md", "status": "pending", "requires": ["x", "y"], "provides": []}
  ]
}'
result=$(echo "$MISSING_PROVIDES" | jq -r "$DEADLOCK_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Missing provides: child blocked (needs y, only x provided)" "b.md" "$result"

# ═══════════════════════════════════════════════════════════════
# 3. endswith() matching for CURRENT_CHILD (filename vs full path)
# ═══════════════════════════════════════════════════════════════
printf "\n=== CURRENT_CHILD endswith matching ===\n"

# The jq query used for provides verification (line 238):
PROVIDES_QUERY='
  [.children[] | select(.path | endswith("/" + $child) or . == $child)] | first | .provides // [] | .[]
'

# 3a. Filename-only match via endswith
result=$(echo "$EXEC_TABLE_CANONICAL" | jq -r \
  --arg child "02-core-feature-plan.md" \
  "$PROVIDES_QUERY" 2>/dev/null || echo "FAIL")
assert_contains "endswith: filename matches full path" "core-feature" "$result"

# 3b. Full path exact match
result=$(echo "$EXEC_TABLE_CANONICAL" | jq -r \
  --arg child "plans/children/02-core-feature-plan.md" \
  "$PROVIDES_QUERY" 2>/dev/null || echo "FAIL")
assert_contains "Exact full path match" "core-feature" "$result"

# 3c. No match for nonexistent child — returns empty
result=$(echo "$EXEC_TABLE_CANONICAL" | jq -r \
  --arg child "99-nonexistent.md" \
  '[.children[] | select(.path | endswith("/" + $child) or . == $child)] | first | .provides // [] | .[]' \
  2>/dev/null || true)
assert_eq "Nonexistent child: empty result" "" "$result"

# 3d. Partial filename should NOT match (substring safety)
result=$(echo "$EXEC_TABLE_CANONICAL" | jq -r \
  --arg child "feature-plan.md" \
  '[.children[] | select(.path | endswith("/" + $child) or . == $child)] | length' \
  2>/dev/null || echo "FAIL")
assert_eq "Partial filename does NOT match (endswith requires /prefix)" "0" "$result"

# ═══════════════════════════════════════════════════════════════
# 4. Status update via endswith matching
# ═══════════════════════════════════════════════════════════════
printf "\n=== Status update via endswith ===\n"

# The jq query for marking child completed (line 270):
STATUS_UPDATE_QUERY='
  .updated_at = $ts |
  (.children[] | select(.path | endswith("/" + $child) or . == $child)) |= (
    .status = $new_status |
    .completed_at = $ts
  )
'

# 4a. Update child status using filename-only CURRENT_CHILD
updated=$(echo "$EXEC_TABLE_CANONICAL" | jq \
  --arg child "01-fix-bugs-plan.md" \
  --arg new_status "completed" \
  --arg ts "2026-03-15T12:00:00Z" \
  "$STATUS_UPDATE_QUERY" 2>/dev/null || echo "FAIL")

result=$(echo "$updated" | jq -r '.children[0].completed_at' 2>/dev/null || echo "FAIL")
assert_eq "Status update: completed_at set via filename match" \
  "2026-03-15T12:00:00Z" "$result"

# 4b. Update pending child to in_progress
updated=$(echo "$EXEC_TABLE_CANONICAL" | jq \
  --arg child "02-core-feature-plan.md" \
  --arg new_status "in_progress" \
  --arg ts "2026-03-15T12:00:00Z" \
  "$STATUS_UPDATE_QUERY" 2>/dev/null || echo "FAIL")

result=$(echo "$updated" | jq -r '.children[1].status' 2>/dev/null || echo "FAIL")
assert_eq "Status update: pending -> in_progress" "in_progress" "$result"

# 4c. Non-matching child leaves table unchanged
updated=$(echo "$EXEC_TABLE_CANONICAL" | jq \
  --arg child "nonexistent.md" \
  --arg new_status "completed" \
  --arg ts "2026-03-15T12:00:00Z" \
  "$STATUS_UPDATE_QUERY" 2>/dev/null || echo "FAIL")

result=$(echo "$updated" | jq -r '[.children[] | select(.status == "pending")] | length' 2>/dev/null || echo "FAIL")
assert_eq "Non-matching child: pending count unchanged" "3" "$result"

# ═══════════════════════════════════════════════════════════════
# 5. Mark next child in_progress via .path exact match
# ═══════════════════════════════════════════════════════════════
printf "\n=== Mark next child in_progress ===\n"

# The jq query for marking next child (line 677):
NEXT_MARK_QUERY='
  .updated_at = $ts |
  (.children[] | select(.path == $child)) |= (
    .status = "in_progress" |
    .started_at = $ts
  )
'

# 5a. Full path match marks child
updated=$(echo "$EXEC_TABLE_CANONICAL" | jq \
  --arg child "plans/children/02-core-feature-plan.md" \
  --arg ts "2026-03-15T12:00:00Z" \
  "$NEXT_MARK_QUERY" 2>/dev/null || echo "FAIL")

result=$(echo "$updated" | jq -r '.children[1].status' 2>/dev/null || echo "FAIL")
assert_eq "Next child marked in_progress via full path" "in_progress" "$result"

result=$(echo "$updated" | jq -r '.children[1].started_at' 2>/dev/null || echo "FAIL")
assert_eq "Next child started_at set" "2026-03-15T12:00:00Z" "$result"

# 5b. Other children unaffected
result=$(echo "$updated" | jq -r '.children[2].status' 2>/dev/null || echo "FAIL")
assert_eq "Sibling child status unchanged" "pending" "$result"

# ═══════════════════════════════════════════════════════════════
# 6. NEXT_CHILD_BASENAME extraction
# ═══════════════════════════════════════════════════════════════
printf "\n=== NEXT_CHILD_BASENAME extraction ===\n"

# The hook extracts basename: NEXT_CHILD_BASENAME="${NEXT_CHILD##*/}"
NEXT_CHILD="plans/children/02-core-feature-plan.md"
NEXT_CHILD_BASENAME="${NEXT_CHILD##*/}"
assert_eq "Basename from full path" "02-core-feature-plan.md" "$NEXT_CHILD_BASENAME"

NEXT_CHILD="simple-name.md"
NEXT_CHILD_BASENAME="${NEXT_CHILD##*/}"
assert_eq "Basename from filename-only" "simple-name.md" "$NEXT_CHILD_BASENAME"

# ═══════════════════════════════════════════════════════════════
# 7. Edge cases
# ═══════════════════════════════════════════════════════════════
printf "\n=== Edge cases ===\n"

# 7a. Empty children array — no next child
EMPTY_CHILDREN='{"children": []}'
result=$(echo "$EMPTY_CHILDREN" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Empty children: no next child" "" "$result"

# 7b. Child with null requires — treated as no deps
NULL_REQUIRES='{
  "children": [
    {"seq": 1, "path": "a.md", "status": "pending", "requires": null, "provides": ["x"]}
  ]
}'
result=$(echo "$NULL_REQUIRES" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "null requires: treated as no deps (executable)" "a.md" "$result"

# 7c. Child with null provides — doesn't contribute to provided set
NULL_PROVIDES='{
  "children": [
    {"seq": 1, "path": "a.md", "status": "completed", "requires": [], "provides": null},
    {"seq": 2, "path": "b.md", "status": "pending", "requires": ["x"], "provides": []}
  ]
}'
result=$(echo "$NULL_PROVIDES" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "null provides: child 02 blocked (no x provided)" "" "$result"

# 7d. Diamond dependency: C requires both A and B
DIAMOND='{
  "children": [
    {"seq": 1, "path": "a.md", "status": "completed", "requires": [], "provides": ["from-a"]},
    {"seq": 2, "path": "b.md", "status": "completed", "requires": [], "provides": ["from-b"]},
    {"seq": 3, "path": "c.md", "status": "pending", "requires": ["from-a", "from-b"], "provides": ["done"]}
  ]
}'
result=$(echo "$DIAMOND" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Diamond dep: C executable when both A and B done" "c.md" "$result"

# 7e. Diamond dependency: only A completed, C still blocked
DIAMOND_PARTIAL='{
  "children": [
    {"seq": 1, "path": "a.md", "status": "completed", "requires": [], "provides": ["from-a"]},
    {"seq": 2, "path": "b.md", "status": "pending", "requires": [], "provides": ["from-b"]},
    {"seq": 3, "path": "c.md", "status": "pending", "requires": ["from-a", "from-b"], "provides": ["done"]}
  ]
}'
result=$(echo "$DIAMOND_PARTIAL" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
# b.md is first executable (no requires), not c.md
assert_eq "Diamond partial: B is next (no requires), C still blocked" "b.md" "$result"

# 7f. Duplicate provides across children — should still satisfy
DUPE_PROVIDES='{
  "children": [
    {"seq": 1, "path": "a.md", "status": "completed", "requires": [], "provides": ["shared"]},
    {"seq": 2, "path": "b.md", "status": "completed", "requires": [], "provides": ["shared"]},
    {"seq": 3, "path": "c.md", "status": "pending", "requires": ["shared"], "provides": []}
  ]
}'
result=$(echo "$DUPE_PROVIDES" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
assert_eq "Duplicate provides: still satisfies requires" "c.md" "$result"

# ═══════════════════════════════════════════════════════════════
# 8. Regression: old .plan/.depends_on schema (should gracefully degrade)
# ═══════════════════════════════════════════════════════════════
printf "\n=== Regression: legacy .plan/.depends_on schema ===\n"

# With the fixed queries, legacy .plan fields are ignored (no .path field).
# .depends_on is also ignored (no .requires field).
# Children with no .requires are treated as "no dependencies" → always executable.
# This is the correct graceful degradation: no silent deadlocks.

# 8a. Legacy schema: all children appear executable (no .requires = no deps)
result=$(echo "$EXEC_TABLE_LEGACY" | jq -r "$TOPO_SORT_QUERY" 2>/dev/null || echo "FAIL")
# .path is missing, so .path // empty returns "". First pending child without .requires
# Since .requires defaults to [], all pending children are executable — first one returned.
# But .path is missing, so result is empty string
# This is acceptable degradation: hook won't find a next child, won't false-deadlock.
TOTAL_COUNT=$(( TOTAL_COUNT + 1 ))
if [[ -z "$result" ]] || [[ "$result" != *".."* ]]; then
  PASS_COUNT=$(( PASS_COUNT + 1 ))
  printf "  PASS: Legacy schema: graceful degradation (no path traversal)\n"
else
  FAIL_COUNT=$(( FAIL_COUNT + 1 ))
  printf "  FAIL: Legacy schema: unexpected result: %s\n" "$result"
fi

# 8b. Legacy schema deadlock query: should NOT produce false deadlock with file paths
result=$(echo "$EXEC_TABLE_LEGACY" | jq -r "$DEADLOCK_QUERY" 2>/dev/null || echo "FAIL")
TOTAL_COUNT=$(( TOTAL_COUNT + 1 ))
# No .requires field → (.requires // []) = [] → any(... | not) on empty = false
# So no children appear as "blocked" → empty result (no false deadlock!)
if [[ -z "$result" ]]; then
  PASS_COUNT=$(( PASS_COUNT + 1 ))
  printf "  PASS: Legacy schema: no false deadlock (empty blocked list)\n"
else
  FAIL_COUNT=$(( FAIL_COUNT + 1 ))
  printf "  FAIL: Legacy schema: false deadlock detected: %s\n" "$result"
fi

# ═══════════════════════════════════════════════════════════════
# Results
# ═══════════════════════════════════════════════════════════════
printf "\n═══════════════════════════════════════════════════\n"
printf "Results: %d/%d passed, %d failed\n" "$PASS_COUNT" "$TOTAL_COUNT" "$FAIL_COUNT"
printf "═══════════════════════════════════════════════════\n"

if [[ "$FAIL_COUNT" -gt 0 ]]; then
  exit 1
fi
exit 0
